# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddyApp', '0005_travelplans_traveler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplans',
            name='traveler',
        ),
        migrations.AddField(
            model_name='travelplans',
            name='travelers',
            field=models.ManyToManyField(related_name='trips', to='TravelBuddyApp.UserRegistration'),
        ),
    ]
